In [110]:
import numpy as np
A = np.array([[3, 1],
              [0, 10],
              [4, -2]])

B = np.array([[4, 5],
              [-3, 1],
              [0, 9]])
print (A)
print (B)


[[ 3  1]
 [ 0 10]
 [ 4 -2]]
[[ 4  5]
 [-3  1]
 [ 0  9]]


In [111]:
print(A[2, 1])

-2


In [112]:
10*A

array([[ 30,  10],
       [  0, 100],
       [ 40, -20]])

In [113]:
A + B

array([[ 7,  6],
       [-3, 11],
       [ 4,  7]])

In [114]:
A = np.array([[3, 1],
              [0, 10],
              [4, -2]])

C = np.array([[10],
             [2],
              [9]])

A + C

array([[13, 11],
       [ 2, 12],
       [13,  7]])

In [115]:
A = np.array([[2, 1],
                [3, 0],
                [5, 4]])

B = np.array([[2, 4],
                [-1, 5]])

print(A)
print(B)

[[2 1]
 [3 0]
 [5 4]]
[[ 2  4]
 [-1  5]]


# 2 * 2 + 1 * (-1) , 2 * 4 + 1 * 5
# 3 * 2 + 0 * (-1) , 3 * 4 + 0 * 5
# 5 * 2 + 4 * (-1) , 5 * 4 + 4 * 5

voi laskea joko:
- np.dot(A, B)
- A @ B
- A.dot(B).dot(B)

In [116]:
A = np.array([[2, 1],
                [3, 0],
                [5, 4]])

B = np.array([[2, 4],
                [-1, 5]])

np.dot(A, B)


array([[ 3, 13],
       [ 6, 12],
       [ 6, 40]])

In [117]:
A.dot(B).dot(B)

array([[ -7,  77],
       [  0,  84],
       [-28, 224]])

Matriisin ( A ) transpoosi (potenssi ( T )) tarkoittaa matriisin ( A ) rivien ja sarakkeiden vaihtamista keskenään. Voit laskea matriisin ( A ) transpoosin käyttämällä NumPy-kirjaston transpose-metodia tai .T-attribuuttia.

- Esimerkki

In [118]:
A = np.array([[2, 1],
              [3, 0],
              [5, 4]])

A_T = A.T
print(A_T)

[[2 3 5]
 [1 0 4]]


In [119]:
np.transpose(A)

array([[2, 3, 5],
       [1, 0, 4]])

In [120]:
A.T

array([[2, 3, 5],
       [1, 0, 4]])

In [121]:
A.shape

(3, 2)

In [122]:
A.T.shape

(2, 3)